=== pryma/epam/Task5/src/main/resources/bankDepositXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.maksim.pryma/bankDepositXMLSchema"
xmlns:bd="http://www.maksim.pryma/bankDepositXMLSchema">
<element name="bank">
	<complexType>
		<sequence>
			<element name="deposit" type="bd:Deposit" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
</element>

<complexType name="Deposit">
	<sequence>
		<element name="bankName" type="bd:BankName"/>
		<element name="depositor" type="string"/>
		<element name="amountOfDeposit" type="integer"/>
		<element name="profitability" type="float"/>
		<element name="timeConstraints" type="integer"/>
	</sequence>
	<attribute name="accountId" type="bd:AccountId" use="required">
		
	</attribute>
	<attribute name="depositType" type="bd:DepositType" use="required">
		
	</attribute>
</complexType>

<complexType name="BankName">
    <simpleContent>
        <extension base="string">
            <attribute name="country" use="required">
                <simpleType>
                    <restriction base="string"/>
                </simpleType>
            </attribute>
        </extension>
    </simpleContent>

</complexType>

<simpleType name="AccountId">
	<restriction base="string">
		<pattern value="[a-zA-z0-9]{10}"/>
	</restriction>
</simpleType>

<simpleType name="DepositType">
	<restriction base="string">
		<enumeration value="posteRestante"/>
		<enumeration value="urgent"/>
		<enumeration value="calculated"/>
		<enumeration value="cumulative"/>
		<enumeration value="saving"/>
		<enumeration value="metallic"/>
	</restriction>
</simpleType>


</schema>

=== pryma/epam/Task5/src/main/resources/bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<bd:bank xmlns:bd="http://www.maksim.pryma/bankDepositXMLSchema"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.maksim.pryma/bankDepositXMLSchema bankDepositXMLSchema.xsd">

    <deposit accountId="1234567890" depositType="calculated">
        <bankName country="US">BSB</bankName>
        <depositor>name1</depositor>
        <amountOfDeposit>100</amountOfDeposit>
        <profitability>7.2</profitability>
        <timeConstraints>12</timeConstraints>
    </deposit>
    <deposit accountId="1234567891" depositType="cumulative">
        <bankName country="BY">BSB</bankName>
        <depositor>name2</depositor>
        <amountOfDeposit>1200</amountOfDeposit>
        <profitability>7.3</profitability>
        <timeConstraints>14</timeConstraints>
    </deposit>

    <deposit accountId="1234567892" depositType="metallic">
        <bankName country="BY">BIB</bankName>
        <depositor>name3</depositor>
        <amountOfDeposit>14000</amountOfDeposit>
        <profitability>7.7</profitability>
        <timeConstraints>24</timeConstraints>
    </deposit>

    <deposit accountId="1234567893" depositType="posteRestante">
        <bankName country="BY">BIB</bankName>
        <depositor>name4</depositor>
        <amountOfDeposit>10000</amountOfDeposit>
        <profitability>7.5</profitability>
        <timeConstraints>15</timeConstraints>
    </deposit>

    <deposit accountId="1234567894" depositType="urgent">
        <bankName country="PL">VTB</bankName>
        <depositor>name5</depositor>
        <amountOfDeposit>1900</amountOfDeposit>
        <profitability>7.1</profitability>
        <timeConstraints>30</timeConstraints>
    </deposit>

    <deposit accountId="1234567895" depositType="saving">
        <bankName country="BY">VEB</bankName>
        <depositor>name6</depositor>
        <amountOfDeposit>19000</amountOfDeposit>
        <profitability>7.8</profitability>
        <timeConstraints>36</timeConstraints>
    </deposit>
    
</bd:bank>
